### PR TITLE
Adds Kapsi / the National Land Survey of Finland topographic map & aerial picture layers

### PR DESCRIPTION
**Pull request by Wnt**
Adds Kapsi / the National Land Survey of Finland topographic map & aerial picture layers #18

### CODE REVIEW

**Comment by dcaliste** [comment]
Thank you for your contribution. If you don't mind, I'll move the three entries a bit lower in the tile source list, because, as far as I've understood these maps only cover Finland (northern Europe ?). I would put them after the public transport map tiles, I think. Would you agree ?

**Comment by Wnt** [comment]
Sure, no problem! I think you should find a way to make all map definitions user configurable via a configuration file or configuration import eventually. See e.g. how Poor Maps has pluggable support for tile providers using .json files:
https://github.com/otsaloma/poor-maps/tree/master/tilesources

**Comment by dcaliste** [comment]
Thanks for the pointer, I'll give a look.

**Comment by dcaliste** [comment]
To allow this, I will have to change internally how tile information are stored, since as you've seen, everything is hard coded with C switches. I need to change also how tile source are stored in the settings (currently an integer which breaks at every change in the tile list). So some works to be done, but quite easy. I put this in my todo list for my next free time slot !

**Comment by Wnt** [comment]
Awesome! Thank you very much for the great software!

**Pull request merged**
